/**
 * Realistic Interactive Mock Agent Simulation Engine
 * Generates step-by-step thoughts, tool calls, tool results, and final synthesized answers.
 */

import { executeTool } from './tools.js';

export async function runMockAgentExecution(agent, userPrompt, onStepCallback) {
  console.log(`[Mock Engine] Starting execution for agent "${agent.name}" with prompt: "${userPrompt}"`);

  const startTime = Date.now();

  // Step 1: Initial Reasoning / Thought Node
  onStepCallback({
    id: `step-1-${Date.now()}`,
    type: 'thought',
    title: 'Reasoning & Task Decomposition',
    time: '0.2s',
    content: `Analyzed user request: "${userPrompt}". \nAccording to my system instruction as ${agent.name}, I need to break this down into actionable tool steps using available capabilities: [${agent.tools.join(', ')}].`
  });

  await new Promise(r => setTimeout(r, 1000));

  // Determine primary tool to invoke based on prompt or agent setup
  let primaryTool = agent.tools[0] || 'web_search';
  let toolParams = {};

  if (primaryTool === 'web_search') {
    toolParams = { query: userPrompt };
  } else if (primaryTool === 'python_interpreter') {
    toolParams = { code: `# Script generated by ${agent.name}\ndef process_data():\n    dataset = [42, 108, 256, 512]\n    print("Calculated summary mean:", sum(dataset)/len(dataset))\n\nprocess_data()` };
  } else if (primaryTool === 'rag_retriever') {
    toolParams = { topic: userPrompt.substring(0, 20) };
  } else {
    toolParams = { input: userPrompt };
  }

  // Step 2: Tool Call Node
  onStepCallback({
    id: `step-2-${Date.now()}`,
    type: 'tool',
    title: `Invoking Tool: ${primaryTool}`,
    time: '0.9s',
    content: `Dispatching function call parameters:`,
    codePayload: JSON.stringify(toolParams, null, 2)
  });

  // Execute actual tool logic
  const toolResult = await executeTool(primaryTool, toolParams);

  // Step 3: Tool Execution Result Node
  onStepCallback({
    id: `step-3-${Date.now()}`,
    type: 'result',
    title: `Tool Output Received (${primaryTool})`,
    time: '1.7s',
    content: `Tool executed successfully with status 200:`,
    codePayload: JSON.stringify(toolResult, null, 2)
  });

  await new Promise(r => setTimeout(r, 1200));

  // Optional Step 4: Secondary Tool Call if agent has multiple tools
  if (agent.tools.length > 1 && (userPrompt.toLowerCase().includes('report') || userPrompt.toLowerCase().includes('data') || userPrompt.toLowerCase().includes('code'))) {
    const secondaryTool = agent.tools[1];
    let secParams = secondaryTool === 'json_parser' 
      ? { json_string: JSON.stringify({ source: primaryTool, status: 'processed', timestamp: Date.now() }) }
      : { query: `${userPrompt} synthesis` };

    onStepCallback({
      id: `step-4-${Date.now()}`,
      type: 'tool',
      title: `Invoking Secondary Tool: ${secondaryTool}`,
      time: '2.3s',
      content: `Refining insights using secondary tool:`,
      codePayload: JSON.stringify(secParams, null, 2)
    });

    const secResult = await executeTool(secondaryTool, secParams);

    onStepCallback({
      id: `step-5-${Date.now()}`,
      type: 'result',
      title: `Secondary Tool Result (${secondaryTool})`,
      time: '3.0s',
      content: `Data validation completed:`,
      codePayload: JSON.stringify(secResult, null, 2)
    });

    await new Promise(r => setTimeout(r, 1000));
  }

  // Step 5: Final Response Node
  const durationSec = ((Date.now() - startTime) / 1000).toFixed(2);
  const synthesizedAnswer = generateSynthesizedAnswer(agent, userPrompt, primaryTool, toolResult);

  onStepCallback({
    id: `step-final-${Date.now()}`,
    type: 'final',
    title: 'Final Agent Synthesis',
    time: `${durationSec}s`,
    content: synthesizedAnswer,
    tokenUsage: {
      promptTokens: 485,
      completionTokens: 290,
      totalTokens: 775,
      estimatedCost: '$0.00015'
    }
  });
}

function generateSynthesizedAnswer(agent, prompt, toolUsed, toolOutput) {
  return `### Agent Response Summary (${agent.name})

Based on the execution of tool \`${toolUsed}\` and systemic verification, here is the answer:

**Key Takeaways & Findings:**
1. **Verified Insights:** Successfully retrieved data for "${prompt}".
2. **Execution Parameters:** Analyzed parameters with low latency (${toolOutput.executionTimeMs || 140}ms).
3. **Structured Outcome:** 
   - All tool constraints were satisfied.
   - The result adheres to system instruction parameters (Temperature: ${agent.temperature}).

> **Recommendation:** The result can be integrated into downstream API webhooks or multi-agent pipelines.`;
}
